### ISSUE TITLE
Purchase domain

### ISSUE THREAD

**Issue by Open-Scribbler** [OpenScribbler/pathoflearn.ing#1]
I wanted to do something fun with the lore for the domain name like using Theopolis Archives or something like that. Though, I ended up realizing that this is PoE, and hardly anyone cares about the lore. So Path of Learning it is!

I also like clever domain names, so pathoflearn.ing was available and I bought it.

**Comment by OpenScribbler** [comment]
I wanted to do something fun with the lore for the domain name like using Theopolis Archives or something like that. Though, I ended up realizing that this is PoE, and hardly anyone cares about the lore. So Path of Learning it is!

I also like clever domain names, so pathoflearn.ing was available and I bought it.
